// flow-typed signature: 6c14920b5d0e46e7cf5d9f0504fd4a5e
// flow-typed version: <<STUB>>/re-bulma_v^0.2.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 're-bulma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-bulma/build/css' {
  declare module.exports: any;
}

declare module 're-bulma/build/styles' {
  declare module.exports: any;
}

declare module 're-bulma/lib/addons' {
  declare module.exports: any;
}

declare module 're-bulma/lib/box' {
  declare module.exports: any;
}

declare module 're-bulma/lib/card' {
  declare module.exports: any;
}

declare module 're-bulma/lib/column' {
  declare module.exports: any;
}

declare module 're-bulma/lib/columns' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card-content' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card-footer-item' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card-footer' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card-header-icon' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card-header-title' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card-header' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card-image' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/card/card' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/heading/heading' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/level/level-item' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/level/level-left' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/level/level-right' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/level/level' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/media/media-content' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/media/media-left' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/media/media-right' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/media/media' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/menu/menu-label' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/menu/menu-link' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/menu/menu-list' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/menu/menu' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/message/message' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/modal/modal' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/nav/nav-container' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/nav/nav-group' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/nav/nav-item' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/nav/nav-toggle' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/nav/nav' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/pagination/page-button' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/panel/panel-block' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/panel/panel-heading' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/panel/panel-tabs' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/panel/panel' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/tabs/tab-group' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/tabs/tab' {
  declare module.exports: any;
}

declare module 're-bulma/lib/components/tabs/tabs' {
  declare module.exports: any;
}

declare module 're-bulma/lib/content' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/addons' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/box' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/button' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/content' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/forms/checkbox' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/forms/control-label' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/forms/form-horizontal' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/forms/input' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/forms/radio' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/forms/select' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/forms/textarea' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/group' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/icon' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/image' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/label' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/notification' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/progress' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/subtitle' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/table' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/tag' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/tbody' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/td' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/tfoot' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/th' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/thead' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/title' {
  declare module.exports: any;
}

declare module 're-bulma/lib/elements/tr' {
  declare module.exports: any;
}

declare module 're-bulma/lib/forms/checkbox' {
  declare module.exports: any;
}

declare module 're-bulma/lib/forms/index' {
  declare module.exports: any;
}

declare module 're-bulma/lib/forms/input' {
  declare module.exports: any;
}

declare module 're-bulma/lib/forms/radio' {
  declare module.exports: any;
}

declare module 're-bulma/lib/forms/select' {
  declare module.exports: any;
}

declare module 're-bulma/lib/forms/textarea' {
  declare module.exports: any;
}

declare module 're-bulma/lib/grid/column' {
  declare module.exports: any;
}

declare module 're-bulma/lib/grid/columns' {
  declare module.exports: any;
}

declare module 're-bulma/lib/grid/tile' {
  declare module.exports: any;
}

declare module 're-bulma/lib/grid/tile/tile' {
  declare module.exports: any;
}

declare module 're-bulma/lib/group' {
  declare module.exports: any;
}

declare module 're-bulma/lib/heading' {
  declare module.exports: any;
}

declare module 're-bulma/lib/helper/helper' {
  declare module.exports: any;
}

declare module 're-bulma/lib/icon' {
  declare module.exports: any;
}

declare module 're-bulma/lib/image' {
  declare module.exports: any;
}

declare module 're-bulma/lib/index' {
  declare module.exports: any;
}

declare module 're-bulma/lib/label' {
  declare module.exports: any;
}

declare module 're-bulma/lib/layout/container' {
  declare module.exports: any;
}

declare module 're-bulma/lib/layout/footer' {
  declare module.exports: any;
}

declare module 're-bulma/lib/layout/hero-body' {
  declare module.exports: any;
}

declare module 're-bulma/lib/layout/hero-foot' {
  declare module.exports: any;
}

declare module 're-bulma/lib/layout/hero-head' {
  declare module.exports: any;
}

declare module 're-bulma/lib/layout/hero' {
  declare module.exports: any;
}

declare module 're-bulma/lib/layout/section' {
  declare module.exports: any;
}

declare module 're-bulma/lib/level' {
  declare module.exports: any;
}

declare module 're-bulma/lib/media-object' {
  declare module.exports: any;
}

declare module 're-bulma/lib/menu' {
  declare module.exports: any;
}

declare module 're-bulma/lib/message' {
  declare module.exports: any;
}

declare module 're-bulma/lib/modal' {
  declare module.exports: any;
}

declare module 're-bulma/lib/nav' {
  declare module.exports: any;
}

declare module 're-bulma/lib/notification' {
  declare module.exports: any;
}

declare module 're-bulma/lib/pagination' {
  declare module.exports: any;
}

declare module 're-bulma/lib/panel' {
  declare module.exports: any;
}

declare module 're-bulma/lib/progress' {
  declare module.exports: any;
}

declare module 're-bulma/lib/styles' {
  declare module.exports: any;
}

declare module 're-bulma/lib/table' {
  declare module.exports: any;
}

declare module 're-bulma/lib/tabs' {
  declare module.exports: any;
}

declare module 're-bulma/lib/tag' {
  declare module.exports: any;
}

declare module 're-bulma/lib/title' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-bulma/build/css.js' {
  declare module.exports: $Exports<'re-bulma/build/css'>;
}
declare module 're-bulma/build/styles.js' {
  declare module.exports: $Exports<'re-bulma/build/styles'>;
}
declare module 're-bulma/lib/addons.js' {
  declare module.exports: $Exports<'re-bulma/lib/addons'>;
}
declare module 're-bulma/lib/box.js' {
  declare module.exports: $Exports<'re-bulma/lib/box'>;
}
declare module 're-bulma/lib/card.js' {
  declare module.exports: $Exports<'re-bulma/lib/card'>;
}
declare module 're-bulma/lib/column.js' {
  declare module.exports: $Exports<'re-bulma/lib/column'>;
}
declare module 're-bulma/lib/columns.js' {
  declare module.exports: $Exports<'re-bulma/lib/columns'>;
}
declare module 're-bulma/lib/components/card/card-content.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card-content'>;
}
declare module 're-bulma/lib/components/card/card-footer-item.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card-footer-item'>;
}
declare module 're-bulma/lib/components/card/card-footer.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card-footer'>;
}
declare module 're-bulma/lib/components/card/card-header-icon.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card-header-icon'>;
}
declare module 're-bulma/lib/components/card/card-header-title.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card-header-title'>;
}
declare module 're-bulma/lib/components/card/card-header.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card-header'>;
}
declare module 're-bulma/lib/components/card/card-image.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card-image'>;
}
declare module 're-bulma/lib/components/card/card.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/card/card'>;
}
declare module 're-bulma/lib/components/heading/heading.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/heading/heading'>;
}
declare module 're-bulma/lib/components/level/level-item.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/level/level-item'>;
}
declare module 're-bulma/lib/components/level/level-left.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/level/level-left'>;
}
declare module 're-bulma/lib/components/level/level-right.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/level/level-right'>;
}
declare module 're-bulma/lib/components/level/level.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/level/level'>;
}
declare module 're-bulma/lib/components/media/media-content.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/media/media-content'>;
}
declare module 're-bulma/lib/components/media/media-left.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/media/media-left'>;
}
declare module 're-bulma/lib/components/media/media-right.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/media/media-right'>;
}
declare module 're-bulma/lib/components/media/media.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/media/media'>;
}
declare module 're-bulma/lib/components/menu/menu-label.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/menu/menu-label'>;
}
declare module 're-bulma/lib/components/menu/menu-link.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/menu/menu-link'>;
}
declare module 're-bulma/lib/components/menu/menu-list.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/menu/menu-list'>;
}
declare module 're-bulma/lib/components/menu/menu.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/menu/menu'>;
}
declare module 're-bulma/lib/components/message/message.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/message/message'>;
}
declare module 're-bulma/lib/components/modal/modal.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/modal/modal'>;
}
declare module 're-bulma/lib/components/nav/nav-container.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/nav/nav-container'>;
}
declare module 're-bulma/lib/components/nav/nav-group.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/nav/nav-group'>;
}
declare module 're-bulma/lib/components/nav/nav-item.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/nav/nav-item'>;
}
declare module 're-bulma/lib/components/nav/nav-toggle.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/nav/nav-toggle'>;
}
declare module 're-bulma/lib/components/nav/nav.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/nav/nav'>;
}
declare module 're-bulma/lib/components/pagination/page-button.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/pagination/page-button'>;
}
declare module 're-bulma/lib/components/pagination/pagination.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/pagination/pagination'>;
}
declare module 're-bulma/lib/components/panel/panel-block.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/panel/panel-block'>;
}
declare module 're-bulma/lib/components/panel/panel-heading.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/panel/panel-heading'>;
}
declare module 're-bulma/lib/components/panel/panel-tabs.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/panel/panel-tabs'>;
}
declare module 're-bulma/lib/components/panel/panel.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/panel/panel'>;
}
declare module 're-bulma/lib/components/tabs/tab-group.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/tabs/tab-group'>;
}
declare module 're-bulma/lib/components/tabs/tab.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/tabs/tab'>;
}
declare module 're-bulma/lib/components/tabs/tabs.js' {
  declare module.exports: $Exports<'re-bulma/lib/components/tabs/tabs'>;
}
declare module 're-bulma/lib/content.js' {
  declare module.exports: $Exports<'re-bulma/lib/content'>;
}
declare module 're-bulma/lib/elements/addons.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/addons'>;
}
declare module 're-bulma/lib/elements/box.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/box'>;
}
declare module 're-bulma/lib/elements/button.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/button'>;
}
declare module 're-bulma/lib/elements/content.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/content'>;
}
declare module 're-bulma/lib/elements/forms/checkbox.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/forms/checkbox'>;
}
declare module 're-bulma/lib/elements/forms/control-label.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/forms/control-label'>;
}
declare module 're-bulma/lib/elements/forms/form-horizontal.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/forms/form-horizontal'>;
}
declare module 're-bulma/lib/elements/forms/input.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/forms/input'>;
}
declare module 're-bulma/lib/elements/forms/radio.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/forms/radio'>;
}
declare module 're-bulma/lib/elements/forms/select.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/forms/select'>;
}
declare module 're-bulma/lib/elements/forms/textarea.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/forms/textarea'>;
}
declare module 're-bulma/lib/elements/group.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/group'>;
}
declare module 're-bulma/lib/elements/icon.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/icon'>;
}
declare module 're-bulma/lib/elements/image.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/image'>;
}
declare module 're-bulma/lib/elements/label.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/label'>;
}
declare module 're-bulma/lib/elements/notification.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/notification'>;
}
declare module 're-bulma/lib/elements/progress.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/progress'>;
}
declare module 're-bulma/lib/elements/subtitle.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/subtitle'>;
}
declare module 're-bulma/lib/elements/table.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/table'>;
}
declare module 're-bulma/lib/elements/tag.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/tag'>;
}
declare module 're-bulma/lib/elements/tbody.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/tbody'>;
}
declare module 're-bulma/lib/elements/td.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/td'>;
}
declare module 're-bulma/lib/elements/tfoot.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/tfoot'>;
}
declare module 're-bulma/lib/elements/th.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/th'>;
}
declare module 're-bulma/lib/elements/thead.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/thead'>;
}
declare module 're-bulma/lib/elements/title.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/title'>;
}
declare module 're-bulma/lib/elements/tr.js' {
  declare module.exports: $Exports<'re-bulma/lib/elements/tr'>;
}
declare module 're-bulma/lib/forms/checkbox.js' {
  declare module.exports: $Exports<'re-bulma/lib/forms/checkbox'>;
}
declare module 're-bulma/lib/forms/index.js' {
  declare module.exports: $Exports<'re-bulma/lib/forms/index'>;
}
declare module 're-bulma/lib/forms/input.js' {
  declare module.exports: $Exports<'re-bulma/lib/forms/input'>;
}
declare module 're-bulma/lib/forms/radio.js' {
  declare module.exports: $Exports<'re-bulma/lib/forms/radio'>;
}
declare module 're-bulma/lib/forms/select.js' {
  declare module.exports: $Exports<'re-bulma/lib/forms/select'>;
}
declare module 're-bulma/lib/forms/textarea.js' {
  declare module.exports: $Exports<'re-bulma/lib/forms/textarea'>;
}
declare module 're-bulma/lib/grid/column.js' {
  declare module.exports: $Exports<'re-bulma/lib/grid/column'>;
}
declare module 're-bulma/lib/grid/columns.js' {
  declare module.exports: $Exports<'re-bulma/lib/grid/columns'>;
}
declare module 're-bulma/lib/grid/tile.js' {
  declare module.exports: $Exports<'re-bulma/lib/grid/tile'>;
}
declare module 're-bulma/lib/grid/tile/tile.js' {
  declare module.exports: $Exports<'re-bulma/lib/grid/tile/tile'>;
}
declare module 're-bulma/lib/group.js' {
  declare module.exports: $Exports<'re-bulma/lib/group'>;
}
declare module 're-bulma/lib/heading.js' {
  declare module.exports: $Exports<'re-bulma/lib/heading'>;
}
declare module 're-bulma/lib/helper/helper.js' {
  declare module.exports: $Exports<'re-bulma/lib/helper/helper'>;
}
declare module 're-bulma/lib/icon.js' {
  declare module.exports: $Exports<'re-bulma/lib/icon'>;
}
declare module 're-bulma/lib/image.js' {
  declare module.exports: $Exports<'re-bulma/lib/image'>;
}
declare module 're-bulma/lib/index.js' {
  declare module.exports: $Exports<'re-bulma/lib/index'>;
}
declare module 're-bulma/lib/label.js' {
  declare module.exports: $Exports<'re-bulma/lib/label'>;
}
declare module 're-bulma/lib/layout/container.js' {
  declare module.exports: $Exports<'re-bulma/lib/layout/container'>;
}
declare module 're-bulma/lib/layout/footer.js' {
  declare module.exports: $Exports<'re-bulma/lib/layout/footer'>;
}
declare module 're-bulma/lib/layout/hero-body.js' {
  declare module.exports: $Exports<'re-bulma/lib/layout/hero-body'>;
}
declare module 're-bulma/lib/layout/hero-foot.js' {
  declare module.exports: $Exports<'re-bulma/lib/layout/hero-foot'>;
}
declare module 're-bulma/lib/layout/hero-head.js' {
  declare module.exports: $Exports<'re-bulma/lib/layout/hero-head'>;
}
declare module 're-bulma/lib/layout/hero.js' {
  declare module.exports: $Exports<'re-bulma/lib/layout/hero'>;
}
declare module 're-bulma/lib/layout/section.js' {
  declare module.exports: $Exports<'re-bulma/lib/layout/section'>;
}
declare module 're-bulma/lib/level.js' {
  declare module.exports: $Exports<'re-bulma/lib/level'>;
}
declare module 're-bulma/lib/media-object.js' {
  declare module.exports: $Exports<'re-bulma/lib/media-object'>;
}
declare module 're-bulma/lib/menu.js' {
  declare module.exports: $Exports<'re-bulma/lib/menu'>;
}
declare module 're-bulma/lib/message.js' {
  declare module.exports: $Exports<'re-bulma/lib/message'>;
}
declare module 're-bulma/lib/modal.js' {
  declare module.exports: $Exports<'re-bulma/lib/modal'>;
}
declare module 're-bulma/lib/nav.js' {
  declare module.exports: $Exports<'re-bulma/lib/nav'>;
}
declare module 're-bulma/lib/notification.js' {
  declare module.exports: $Exports<'re-bulma/lib/notification'>;
}
declare module 're-bulma/lib/pagination.js' {
  declare module.exports: $Exports<'re-bulma/lib/pagination'>;
}
declare module 're-bulma/lib/panel.js' {
  declare module.exports: $Exports<'re-bulma/lib/panel'>;
}
declare module 're-bulma/lib/progress.js' {
  declare module.exports: $Exports<'re-bulma/lib/progress'>;
}
declare module 're-bulma/lib/styles.js' {
  declare module.exports: $Exports<'re-bulma/lib/styles'>;
}
declare module 're-bulma/lib/table.js' {
  declare module.exports: $Exports<'re-bulma/lib/table'>;
}
declare module 're-bulma/lib/tabs.js' {
  declare module.exports: $Exports<'re-bulma/lib/tabs'>;
}
declare module 're-bulma/lib/tag.js' {
  declare module.exports: $Exports<'re-bulma/lib/tag'>;
}
declare module 're-bulma/lib/title.js' {
  declare module.exports: $Exports<'re-bulma/lib/title'>;
}
